// Type generation for exported scene data (future TS export format)
// This module defines the types that would be generated alongside TS exports.

export const DECORATION_ENTITY_TYPE = `export interface DecorationEntity {
  id: string
  asset: string
  position: [number, number, number]
  rotation: [number, number, number]
  scale: [number, number, number]
}`

export const COLLIDER_ENTITY_TYPE = `export interface ColliderEntity {
  id: string
  shape: "cylinder" | "box"
  position: [number, number, number]
  rotation: [number, number, number]
  dimensions: [number, number, number]
}`

export const DECORATION_LAYER_TYPE = `export interface DecorationLayer {
  scene: string
  layer: string
  type: "decoration"
  entities: DecorationEntity[]
}`

export const COLLIDER_LAYER_TYPE = `export interface ColliderLayer {
  scene: string
  layer: string
  type: "collider"
  entities: ColliderEntity[]
}`

export function generateTypesFile(): string {
  return [
    '// Auto-generated by Goblin Editor',
    DECORATION_ENTITY_TYPE,
    '',
    COLLIDER_ENTITY_TYPE,
    '',
    DECORATION_LAYER_TYPE,
    '',
    COLLIDER_LAYER_TYPE,
  ].join('\n')
}
